# Generated by Django 4.2.4 on 2023-09-08 18:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 8, 21, 41, 29, 609301), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликован ли'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='views_counter',
            field=models.IntegerField(default=0, verbose_name='Количество просмотров'),
        ),
    ]
