# Generated by Django 4.2.4 on 2023-09-18 17:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_created_at_alter_blog_is_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 18, 20, 51, 41, 612184), verbose_name='Дата создания'),
        ),
    ]
