# Generated by Django 4.2.4 on 2023-09-20 16:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 20, 19, 34, 29, 706619), verbose_name='Дата создания'),
        ),
    ]
