# Generated by Django 4.2.4 on 2023-09-25 17:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 25, 20, 23, 10, 767328), verbose_name='Дата создания'),
        ),
    ]
