# Generated by Django 4.2.4 on 2023-09-26 17:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_version_options_alter_product_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 26, 20, 48, 7, 437580), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='last_change_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 26, 20, 48, 7, 437580), verbose_name='Дата последнего изменения'),
        ),
    ]
